Remember to load ya packages or else its going to be a shit show

In [4]:
import numpy as np

We finna do some slicing and indexing 


In [5]:
# first we create an array that will utilize the arange function for numpy 
arr = np.arange(10)
print arr

[0 1 2 3 4 5 6 7 8 9]


Remember in python we index by starting at 0 so arange creates n-1 which is 9! Let's call up the value 5 for shits and giggles

In [7]:
print arr[5]

5


So next we index by calling more than one at a time using the : let's try 4-7

In [10]:
print arr[4:7]

[4 5 6]


In [14]:
# Next let's change the values for a group of indices! Notice how it changes them all super important to differentiate this
# Especially when using a shit ton of rows in analysis 
arr[2:4] = 42
print arr

[ 0  1 42 42  4  5  6  7  8  9]


here we'll how np arrays work in that even though we created a new object named arr_slice. when we change the value for that variable the original object (arr) will also have these changes! SUPER IMPORTANT TO KEEP IN MIND WHEN DOING ANALYSIS 

In [21]:
arr_slice = arr[2:4]
print arr_slice[1]
arr_slice[1] = 12345
print arr

42
[    0     1    42 12345     4     5     6     7     8     9]


Holy shit look at that!! Remember this shit. Now we do other shit that's super important!

In [25]:
arr_slice[:] = 69
print arr

[ 0  1 69 69  4  5  6  7  8  9]


See that shit!! important af. This is how you recognize the (I'm assuming) difference between numpy arrays and pandas data frames. Since the book keeps telling me that this is how numpy is set apart from other forms of data storage. WHich makes a shit ton of sense cus I'm use to data frames with r where once you subset an object it is its own entity!

The way you make a copy you need to explicitly make a copy!!!! 


In [32]:
arr_copy = arr[2:4].copy()
print arr_copy
arr_copy[:] = 14
# First we print the copy to make sure the values changed to 14
print arr_copy
# Now we print the original array to see that was left untouched
print arr 

[69 69]
[14 14]
[ 0  1 69 69  4  5  6  7  8  9]


Now that we're done with the easy shit let's go balls deep into the good shit. The shit with dimensions!!!

In [37]:
# First we create the 2d array 
arr2d = np.array([[1, 2, 3], [77, 109, 23], [13, 90, 33]])
print "Here's the array"
print arr2d
# Let's scope out the indexing for this bitch
print "Index selecting for 2d array"
print arr2d[2]

Here's the array
[[  1   2   3]
 [ 77 109  23]
 [ 13  90  33]]
Index selecting for 2d array
[13 90 33]


Next we access individual values within the 2d array which is done more than one way but I'll mention which is the most used 

In [40]:
# Here's a way you can do it but its not the recommended way!
print "A way of doing it (not recommended)"
print arr2d[0][2]
# Here the actual way to do it
print "Proper way, son. Facts b"
print arr2d[0, 2]

A way of doing it (not recommended)
3
Proper way, son. Facts b
3


NOW WE DO SOME 3D SHIT YO FUCK WIT YO SHIT

In [77]:
arr3d = np.array([[[1, 5, 3],[5, 7, 2]], [[12, 6, 666], [0, 54, 8, 54]]])
print arr3d

[[[1, 5, 3] [5, 7, 2]]
 [[12, 6, 666] [0, 54, 8, 54]]]


Let's fuck with some indexing and slicing on this bad boy here

In [71]:
print arr3d[0]

[[1, 5, 3] [5, 7, 2]]


Now let's make a copy of this 3d array and do shit with it

In [96]:
old_values = arr3d[0].copy()
print "Here's the old values"
print old_values
arr3d[0] = [[42, 42, 42],[42, 42, 42]]
print "Here's the og array"
print arr3d

Here's the old values
[[42, 42, 42] [42, 42, 42]]
Here's the og array
[[[42, 42, 42] [42, 42, 42]]
 [[12, 6, 666] [0, 54, 8, 54]]]


Let's fuck some shit up

In [99]:
# Here we change the values because we fucking can 
print "Here's the og object"
print arr3d
# Next we change the values according to the old values and the object chagnes accordingly!!!! FUCK YESS!!
arr3d[0] = old_values
print "Here's transformation I did"
print arr3d
# Now let's do ome indexing that will make data 1d
print "Here are values whose indices start with (1, 0)"
print arr3d[1, 0]

Here's the og object
[[[42, 42, 42] [42, 42, 42]]
 [[12, 6, 666] [0, 54, 8, 54]]]
Here's transformation I did
[[[42, 42, 42] [42, 42, 42]]
 [[12, 6, 666] [0, 54, 8, 54]]]
Here are values whose indices start with (1, 0)
[12, 6, 666]


# Next we index with slicing 


In [103]:
# I need to print the original array because I probably wouldn't have context 
print "The original array"
print arr
print "Here we slice by index"
print arr[1:6]

The original array
[ 0  1 69 69  4  5  6  7  8  9]
Here we slice by index
[ 1 69 69  4  5]


In [107]:
print "Here's the 2d array"
print arr2d
print "Here's some playing with the index"
print arr2d[:2]

Here's the 2d array
[[  1   2   3]
 [ 77 109  23]
 [ 13  90  33]]
Here's some playing with the index
[[  1   2   3]
 [ 77 109  23]]
