# Python for Data Analysis
## Author Wes McKinney 

### Jupyter Notebook Created for following tutorial on DA for Python
(Book for purchase can be found here: http://shop.oreilly.com/product/0636920023784.do)

+ Raul Eulogio, 10/01/2016

## Chapter 4: NumPy Basics
### Arrays and Vectorized Computation

Remember to load ya packages or else its you'll get a lot of errors later on

In [1]:
import numpy as np
from numpy.random import randn
import matplotlib.pyplot as plt

We going to do some slicing and indexing 


In [21]:
# first we create an array that will utilize the arange function for numpy 
arr = np.arange(10)
print arr

[0 1 2 3 4 5 6 7 8 9]


Remember in python we index by starting at 0 so arange creates n-1 which is 9! Let's call up the value 7 to show this


In [4]:
print arr[7]

7


So next we index by calling more than one at a time using the : let's try index  4 thru 7

In [4]:
print arr[4:7]

[4 5 6]


In [5]:
# Next let's change the values for a group of indices! 
# Notice how it changes them all super important to differentiate this!
# Especially when using a shit ton of rows in analysis 
arr[2:4] = 42
print arr

[ 0  1 42 42  4  5  6  7  8  9]


here we'll see how np arrays work in that even though we created a new object named arr_slice. when we change the value for that variable the original object (arr) will also have these changes! SUPER IMPORTANT TO KEEP IN MIND WHEN DOING ANALYSIS. Idk if pandas does the same but I'm not use to that

In [6]:
arr_slice = arr[2:4]
print arr_slice[1]
arr_slice[1] = 12345
print arr

42
[    0     1    42 12345     4     5     6     7     8     9]


Look at that!! Remember this shit. Now we do other shit that's super important!

In [7]:
arr_slice[:] = 69
print arr

[ 0  1 69 69  4  5  6  7  8  9]


See that shit!! important af. This is how you recognize the (I'm assuming) difference between numpy arrays and pandas data frames. Since the book keeps telling me that this is how numpy is set apart from other forms of data storage. WHich makes a shit ton of sense cus I'm use to data frames with r where once you subset an object it is its own entity!

The way you make a copy you need to explicitly make a copy!!!! 


In [8]:
arr_copy = arr[2:4].copy()
print arr_copy
arr_copy[:] = 14
# First we print the copy to make sure the values changed to 14
print arr_copy
# Now we print the original array to see that was left untouched
print arr 

[69 69]
[14 14]
[ 0  1 69 69  4  5  6  7  8  9]


Now that we're done with the easy shit let's go balls deep into the good shit. The shit with dimensions!!!

In [9]:
# First we create the 2d array 
arr2d = np.array([[1, 2, 3], [77, 109, 23], [13, 90, 33]])
print "Here's the array"
print arr2d
# Let's scope out the indexing for this bitch
print "Index selecting for 2d array"
print arr2d[2]

Here's the array
[[  1   2   3]
 [ 77 109  23]
 [ 13  90  33]]
Index selecting for 2d array
[13 90 33]


Next we access individual values within the 2d array which is done more than one way but I'll mention which is the most used 

In [10]:
# Here's a way you can do it but its not the recommended way!
print "A way of doing it (not recommended)"
print arr2d[0][2]
# Here the actual way to do it
print "Proper way, son. Facts b"
print arr2d[0, 2]

A way of doing it (not recommended)
3
Proper way, son. Facts b
3


# NOW WE DO SOME 3D SHIT TO FUCK WIT YO SHIT

In [12]:
arr3d = np.array([[[1, 5, 3],[5, 7, 2]], [[12, 6, 666], [0, 54, 8, 54]]])
print arr3d

[[[1, 5, 3] [5, 7, 2]]
 [[12, 6, 666] [0, 54, 8, 54]]]


Let's fuck with some indexing and slicing on this bad boy here

In [13]:
print arr3d[0]

[[1, 5, 3] [5, 7, 2]]


Now let's make a copy of this 3d array and do shit with it

In [14]:
old_values = arr3d[0].copy()
print "Here's the old values"
print old_values
arr3d[0] = [[42, 42, 42],[42, 42, 42]]
print "Here's the og array"
print arr3d

Here's the old values
[[1, 5, 3] [5, 7, 2]]
Here's the og array
[[[42, 42, 42] [42, 42, 42]]
 [[12, 6, 666] [0, 54, 8, 54]]]


Let's fuck some shit up

In [15]:
# Here we change the values because we fucking can 
print "Here's the og object"
print arr3d
# Next we change the values according to the old values and the object chagnes accordingly!!!! FUCK YESS!!
arr3d[0] = old_values
print "Here's transformation I did"
print arr3d
# Now let's do ome indexing that will make data 1d
print "Here are values whose indices start with (1, 0)"
print arr3d[1, 0]

Here's the og object
[[[42, 42, 42] [42, 42, 42]]
 [[12, 6, 666] [0, 54, 8, 54]]]
Here's transformation I did
[[[1, 5, 3] [5, 7, 2]]
 [[12, 6, 666] [0, 54, 8, 54]]]
Here are values whose indices start with (1, 0)
[12, 6, 666]


# Next we index with slicing 


In [16]:
# I need to print the original array because I probably wouldn't have context 
print "The original array"
print arr
print "Here we slice by index"
print arr[1:6]

The original array
[ 0  1 69 69  4  5  6  7  8  9]
Here we slice by index
[ 1 69 69  4  5]


In [17]:
print "Here's the 2d array"
print arr2d
print "Here's some playing with the index"
print arr2d[:2, 1:]

Here's the 2d array
[[  1   2   3]
 [ 77 109  23]
 [ 13  90  33]]
Here's some playing with the index
[[  2   3]
 [109  23]]


# Boolean Indexing
Here we're going to fuck with some arrays that have repeated values (in our case strings) 

In [20]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print names
print data # Should give us a 7 by 4 matrix!

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.1489931  -0.04264036  0.02788588 -1.07346032]
 [-0.58804556  0.17743556  1.4574384  -0.37701545]
 [ 0.22374794  0.0990523  -1.47524875 -1.56494597]
 [-0.68889717  0.19494742  1.18597277  0.18799693]
 [ 1.04208164 -0.29814606  0.09276226 -2.36575898]
 [-0.05149693 -0.08322902  0.31386553  1.65567775]
 [-0.86803185  1.44614979 -0.68222611 -0.93578424]]


Let's play around with some commands to get familiar with indexing with boolean statements! 
The following statement will look into the array and output whether its 'Bob' or not.
Intuitively it outputs 'True' if the value is 'Bob', 'False' if it's not 'Bob'

In [24]:
print names == 'Bob'

[ True False False  True False False False]


In [30]:
print data[names == 'Bob']
print 'Do the same for will'
print data[names == 'Will']
print 'Last but not least Joe'
print data[names == 'Joe']

[[ 0.1489931  -0.04264036  0.02788588 -1.07346032]
 [-0.68889717  0.19494742  1.18597277  0.18799693]]
Do the same for will
[[ 0.22374794  0.0990523  -1.47524875 -1.56494597]
 [ 1.04208164 -0.29814606  0.09276226 -2.36575898]]
Last but not least Joe
[[-0.58804556  0.17743556  1.4574384  -0.37701545]
 [-0.05149693 -0.08322902  0.31386553  1.65567775]
 [-0.86803185  1.44614979 -0.68222611 -0.93578424]]


## Universal Functions: Fast Element-wise Array Functions

+ 11/15/2016

A universal function, or *ufunc*, is a function that performs elementwise operations on data in ndarrays. Let's see it in motion through examples:

In [18]:
arr = np.arange(10)
print("Here's our function arr:")
print(arr)

# Square root function pretty self-explanatory
print("Here's the output for the ufunc sqrt:")
print(np.sqrt(arr))

# Exponential function like-wise
print("Here's the output for the ufunc exp:")
print(np.exp(arr))


Here's our function arr:
[0 1 2 3 4 5 6 7 8 9]
Here's the output for the ufunc sqrt:
[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]
Here's the output for the ufunc exp:
[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03
   2.98095799e+03   8.10308393e+03]


So these functions are referred to as *unary ufuncs*, because they only **take in one array**.

Other *ufuncs* like `add` or `maximum`, take on 2 arrays as parameters, so they are called *binary ufuncs* and return a single array. Again let's see an example:

In [30]:
# Here we use randn to create two arrays 
x = np.random.randn(8)
y = np.random.randn(8)

print("Here's x!")
print(x)
print("Here's y!")
print(y)

np.maximum(x, y) # element-wise maximum so yeah binary ufunc in action!


Here's x!
[ 0.84525324  0.5564459  -0.48976689 -0.60057097  1.75557823  1.72217474
 -0.50008848 -0.77313331]
Here's y!
[ 0.27643101 -0.23731781  0.69172893  0.10385902 -0.15809887 -0.1790136
 -0.31189244  0.82841644]


array([ 0.84525324,  0.5564459 ,  0.69172893,  0.10385902,  1.75557823,
        1.72217474, -0.31189244,  0.82841644])

In the text book you can get a list of both *unary* and *binary ufuncs* pg. 96! 


## Data Processing Using Arrays 
The process of using expressions to replace the use of loops is called *vectorization*, and come in handy in **NumPy**. 

Example: Suppose we want to do `sqrt(x^2 + y^2)` across a grid of values. The `np.meshgrid` function takes two 1D arrays and produces two 2D matrices corresponding to all pairs of `(x, y)` as follows: 


In [4]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points

xs, ys = np.meshgrid(points, points)

ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [5]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [15]:
plt.imshow(z, cmap=plt.cm.gray);plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
plt.show()

![](img/figure_1.png)

## Mathematical and Statistical Methods
Probably most relevant part of this chapter for me and doing data related shit!!!!

In [16]:
arr = np.random.randn(5, 4)

In [17]:
arr.mean()

0.13957669776061438

In [18]:
np.mean(arr)

0.13957669776061438

In [19]:
arr.sum()

2.7915339552122878